# Generated by Django 5.1.1 on 2024-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='consultation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='last_vaccine_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccine',
            field=models.CharField(blank=True, choices=[('V8', 'V8'), ('V10', 'V10')], max_length=3, null=True),
        ),
    ]
