# Generated by Django 5.1.1 on 2024-10-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPetApp', '0002_pet_consultation_date_pet_last_vaccine_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vaccine',
            field=models.CharField(blank=True, choices=[('V8', 'V8'), ('V10', 'V10'), ('Não Vacinado', 'Não Vacinado')], max_length=15, null=True),
        ),
    ]
